3ds 2.0 flow
gfsx0259/payment-page-mock pull request #16
Opened 2022-07-29 15:34 UTC by ruslanpetunin

2022-08-17 10:03 UTC, gfsx0259 requested changes

2022-08-17 10:03 UTC, gfsx0259 commented on src/server/src/Stub/ActionController.php
> +    public function checkAcs(
Разве это не тоже самое, что и `completeAcs`?

2022-08-17 10:03 UTC, gfsx0259 commented on src/server/src/Stub/DummyPageController.php
> +     * @throws \Psr\SimpleCache\InvalidArgumentException
`use`

2022-08-17 10:03 UTC, gfsx0259 commented on src/server/src/Stub/DummyPageController.php
> +    public function renderAcsForm(CurrentRoute $currentRoute): ResponseInterface
Для чего нужен третий шаг, почему сразу не сделать редирект с `cres` на `acs_return_url.return_url` сразу из второй формы?

2022-08-17 10:03 UTC, gfsx0259 commented on src/server/src/Stub/DummyPageController.php
> +     * @throws \Psr\SimpleCache\InvalidArgumentException
`use`

2022-08-17 10:03 UTC, gfsx0259 commented on src/server/src/Stub/Service/ActionFactory.php
> +            } elseif ($callback->get('threeds2.iframe.url')) {
Разве `threeds2.redirect.params` и `threeds2.iframe.params` не являются как раз данными, на которые можно завязать установку экшена и его завершение? Как `md` в обычном acs флоу. Есть ощущение, что это должно быть здесь, а валидация из `DummyPageController` должна уйти, поправь, если ошибаюсь

2022-08-18 09:23 UTC, ruslanpetunin commented on src/server/src/Stub/Service/ActionFactory.php
> +            } elseif ($callback->get('threeds2.iframe.url')) {
В этом случае нет, потому что там происходит такой флоу:

1. Мок отдает эти парамсы, создавая экшн
2. ПП открывает айфрейм с этими парамсами
3. Мок показывает форму (тут экшн не завершается, т.к. мы не переводим еще курсор)
4. Форма отправляется на ПП
5. ПП отправляет запрос на мок, в котором из идентификационных полей есть только payment_id
6. После этого запроса мы завершаем экшн и переводим курсор

т.е. у нас в момент завершения экшена нет этих парамсов

2022-08-18 19:38 UTC, gfsx0259 commented on src/server/src/Stub/ActionController.php
> +    public function completeAcs(ServerRequestInterface $request): ResponseInterface
Здесь я имел в виду, что если методы одинаковые, можно просто в роутинге указать один и тот же
![image](https://user-images.githubusercontent.com/13059738/185480011-0ee22271-b786-4ac0-afb1-327146a4cb7d.png)

2022-08-19 10:11 UTC, ruslanpetunin commented on src/server/src/Stub/ActionController.php
> +    public function completeAcs(ServerRequestInterface $request): ResponseInterface
Там все таки разные экшены завершаются, ну и по смыслу это разные действия. По этому оба роута завязать на один метод, мне кажется, не оч идея

2022-08-20 14:03 UTC, gfsx0259 commented on src/server/src/Stub/ActionController.php
> +    public function completeAcs(ServerRequestInterface $request): ResponseInterface
Но если оба экшена завершаются одинаково по `paymentId`, разве важно, что это разные экшены?)

2022-08-22 08:38 UTC, ruslanpetunin commented on src/server/src/Stub/ActionController.php
> +    public function completeAcs(ServerRequestInterface $request): ResponseInterface
по идеи важно, т.к. если один из флоу будет правиться, то велика вероятность задеть другой. Врятли ты будешь ожидать, что метод ActionController::completeAcs отвечает за два роута (3ds_result, 3ds_check_iframe) из разных флоу

2022-08-22 08:38 UTC, ruslanpetunin commented on src/server/src/Stub/ActionController.php
> +    public function completeAcs(ServerRequestInterface $request): ResponseInterface
но я поправил)

2022-08-22 09:56 UTC, closed without merging