WIP Resource crud
gfsx0259/payment-page-mock pull request #22
Opened 2022-08-16 14:31 UTC by ruslanpetunin

2022-08-17 14:05 UTC, gfsx0259 commented on src/server/src/Stub/StaticController.php
> +    ) {
`: ResponseInterface`

2022-08-17 14:06 UTC, gfsx0259 commented on src/client/src/components/common/NavBar.vue
> +            return items.map((item) => {
https://user-images.githubusercontent.com/13059738/185154770-5712847c-5797-42e3-af0b-8da8243dbd7d.mp4

2022-08-18 05:39 UTC, gfsx0259 requested changes

2022-08-18 05:39 UTC, gfsx0259 commented on src/server/src/Stub/Service/Callback/OverrideProcessor.php
> +    private function getResources(): iterable
Правильно ли я понял, что это нужно, так как у нас два вызова `getResources`? Разве `cycle` не кеширует всё в рамках одного запроса? Кажется, лишним.

2022-08-18 05:39 UTC, gfsx0259 commented on src/server/src/Stub/Service/Callback/OverrideProcessor.php
> +        }
А почему бы нам вместо вставок в `schema` и `source` не сделать так вторым шагом:
```
foreach ($this->getResources() as $resource) {
        $callback->replace(
            '{{' . $resource->getTemplateVariable() . '}}',
            $this->generateResourceUrl($resource)
        );
}
```
Так или иначе, в `source` мы вставляем ресурсы беузсловно, а так у нас нету необходимости дважды вызывать `getResources` и читается проще. Да и вообще появляется возможность вынести всё, что касается обогащения коллбека ресурсами в отдельный `ResourceOverrideProcessor`.

Плюс, нужен ли вообще `strtolower`?

2022-08-18 05:39 UTC, gfsx0259 commented on src/server/src/Stub/Entity/Resource.php
> +        return $this->getAlias() . '_RESOURCE';
В `alias` можно ввести в любом регистре, не нужен ли здесь `uppercase`, чтобы плейсхолдеры соответствовали остальным? 
![image](https://user-images.githubusercontent.com/13059738/185301617-65a45806-9ec9-49f4-84fc-8f4f80abc558.png)

2022-08-18 05:39 UTC, gfsx0259 commented on src/server/src/Stub/Api/ResourceController.php
> +            $resources[] = [
Ты против `toArray` в сущностях?

2022-08-18 05:39 UTC, gfsx0259 commented on src/server/src/Stub/Api/ResourceController.php
> +use App\Stub\Entity\Stub;
Import 'App\Stub\Entity\Stub' is never used

2022-08-18 06:17 UTC, gfsx0259 commented on src/client/src/store/ResourceStore.js
> +            validateForm: ({state, commit}) => {
Нам бы и в другие формы добавить валидацию, может возьмём что-нибудь готовое вроде https://vuelidate-next.netlify.app/#installation?

2022-08-18 09:37 UTC, ruslanpetunin commented on src/server/src/Stub/Entity/Resource.php
> +        return $this->getAlias() . '_RESOURCE';
я добавил валидацию, нельзя в любом регистре. Ты перебилживал фронт? там валидация появилась

2022-08-18 11:14 UTC, ruslanpetunin commented on src/server/src/Stub/Api/ResourceController.php
> +            $resources[] = [
неа)

2022-08-18 11:30 UTC, ruslanpetunin commented on src/client/src/store/ResourceStore.js
> +            validateForm: ({state, commit}) => {
с текущей реализацией формы в модалке это сложно сделать. У нас получается отправка формы инициируется из модалки, а не из самой формы. Если мы заюзаем эту библу, то она будет максимально костыльно выглядеть. 

Чтобы ее по нормальному использовать, то можно сделать например так:

1. Делаем компонент ModalForm
2. Этот компонент принимает конфиг для инпутов, которые он будет выводить
3. Этот компонент умеет валидировать эти инпуты

2022-08-18 11:32 UTC, ruslanpetunin commented on src/client/src/store/ResourceStore.js
> +            validateForm: ({state, commit}) => {
делаем так?

2022-08-19 05:26 UTC, gfsx0259 approved these changes

2022-08-19 05:26 UTC, gfsx0259 commented on src/client/src/store/ResourceStore.js
> +            validateForm: ({state, commit}) => {
Ладно, давай пока так оставим

2022-08-20 13:52 UTC, gfsx0259 approved these changes

2022-08-20 13:52 UTC, merged